### ISSUE TITLE
Create a space per guild

### ISSUE THREAD

**Issue by wiwie** [matrix-discord/mx-puppet-discord#179]
Although currently still in beta, I find spaces very useful for organizing rooms.
Especially when bridging to other platforms with similar concepts, such as guilds aka server in discord.

Would it be possible to collect all bridged channels in a space? Doing this for all of them manually is quite tedious.

**Comment by dsonck92** [comment]
Just as a heads up, I'm currently implementing this. To indicate what I want to include as support:

 - Defining a "root" space for the puppet itself, allowing you to group all of Discord under a Discord space
 - Creating subspaces for each guild, or if the puppet doesn't have a space itself, they become root spaces
 - Creating another layer, optionally, for each category, since there are some servers that have a lot of channels which are properly grouped.

Most of this logic will likely end up in the mx-puppet-bridge library, so any bridges derived from there can benefit as well.

**Comment by mossymossmoss** [comment]
This is the only feature stopping me from using this full time, it's great to see that it's being worked on! Are then any updates on how it's coming along?

**Comment by IeuanK** [comment]
Any update on this? I use Matrix for WhatsApp and IRC, would be great to have my primary Discord channels also run through it, but there are too many not to organize them better

**Comment by dsonck92** [comment]
Currently I still need to fix the excessive creation of rooms. For perspective, a guild with 5 channels spread across 2 categories should (with all features enabled) create 8 rooms (5 for channels, 2 for category spaces and 1 for guild space). However, due to concurrency bugs and improper exception handling, the code created around 1000 rooms. So I want to fix this bug first

**Comment by dsonck92** [comment]
One improvement on this, it does seem to only succeed with 8 rooms (aka send 8 invites) so the concurrency bug seems fixed. However looking at the admin tool for synapse I did notice it created way too many rooms. It's probably a combination of synapse getting overwhelmed and the bridge not realizing the room creation was successful. All of which should be handled better

**Comment by mossymossmoss** [comment]
Do keep us updated if you make any progress, and thanks for the work that you have done so far!

**Comment by jZ7He56RkPTYABUjfww4** [comment]
I second this feature. It would be a great way to keep rooms organized.

**Comment by shalzz** [comment]
This is something that could work with or is already working with https://gitlab.com/beeper/mx-puppet-monorepo?

**Comment by dsonck92** [comment]
As far as I know, they don't have this support yet and I don't know that codebase (I also don't fully agree with the choice of https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/d8a19e5bf9526e7eb2cc0f1247c877aab7c19e1f to migrate to their fork). I have yet to decide how I proceed with the support of this. There's something to say for beepers fork, and me taking that as base to continue my work (internally I also have a monorepo for local development) and officially deprecating these. But this has not been discussed with Beeper and whether they are open to accepting the community it brings.

In any case, for personal reasons (taxing job) I've had less than optimal time to maintain this which I understand is the main reason for the migration towards beeper's fork. However, I did realize this at last and considering I'm switching jobs, there may be more time outside working hours to actually spend more effort on finishing this, and maintaining things. (But that will be done after april, so perhaps I find more time earlier, perhaps not, perhaps not at all, but that's where I'm standing)

**Comment by Sorunome** [comment]
> But this has not been discussed with Beeper and whether they are open to accepting the community it brings.

yes, they have, soru did discuss it and they did not want to adopt the community.

**Comment by shalzz** [comment]
I see, its unfortunate beeper has a paid service but is unwilling to accept community contributions now after forking a community project (don't know how well they are compliant with the licenses and attributing past authors) especially since their paid users would want the same features?
Perhaps consider setting up a funding/donation page via open collective, GH sponsors, etc.

**Comment by dsonck92** [comment]
I believe it was not so much not accepting community contributions, but also standing in for offering support. I'm pretty sure I can submit the spaces feature I'm working on to Beeper, but offering community support won't be done by Beeper. At least that's what I understood from Soru when I talked about Beeper. But she can inform more about that.

So in that scenario, I don't find it appropriate to submit this feature to beeper and say "this github original project is now deprecated, go to Beeper". But that's just my view. In any case, I will, at some point, definitely continue with this as this was my original plan months ago and still is, once I have the ability again to do so (I'm pretty sure it comes, just don't know when).

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/179
