### ISSUE TITLE
Sending an edit caused an echo back to matrix

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#48]
![image](https://user-images.githubusercontent.com/1342360/72819487-41b58500-3c65-11ea-8a71-8a4f434edb47.png)

Supposedly this was fixed in https://github.com/matrix-discord/mx-puppet-discord/issues/24, but I just got it again on 2b196e3d5fbd6bfac2ef6a0bc7b0f99a15da3f0f.

Server logs don't go back far enough to see what happened there unfortunately.

I'm not able to reproduce this.

**Comment by Sorunome** [comment]
The timestamps suggest a network lag? Unfortunately deduping works by saying that all messages coming in that channel after the next <x amount of time> have to wait until we can know which IDs to filter out. If there is a network lag it means echo backs can happen. There isn't really a way around it :/

The underlying problem is that discord can send you the new message via message stream *before* you get the ID back from sending the message to know which message you just sended

**Comment by Sorunome** [comment]
probably fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/4327edf2194445b62e359caca6ace249ee5de004
