### ISSUE TITLE
Images not put between text messages correctly

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#70]
![image](https://user-images.githubusercontent.com/1342360/80624371-7e9ece00-8a43-11ea-926b-bcc56bada75f.png)

![image](https://user-images.githubusercontent.com/1342360/80624388-8494af00-8a43-11ea-8aba-fdab512d7932.png)

When someone is sending messages and images, the images can end up between the wrong messages easily.

Seems like we don't block bridging messages to matrix while waiting for an image to send?

**Comment by TheDiscordian** [comment]
Discord has an image with a message attached as 1 object, Matrix has it as 2. I don't think there's a way for the bridge to know with 100% certainty that the text was absolutely supposed to be before the image, unless the user ensures the ordering themselves.

Even then, is it ideal to block while the bridge uploads an image, or to allow other text to go through? I'd prefer the text goes through, and the image shows up whenever. Mostly because I believe in larger rooms, this could cause a lot of message bursts, which is even less ideal.

I could be wrong, but those are the pitfalls I understand about this issue.

**Comment by anoadragon453** [comment]
I believe Discord always puts the message above the image, no?

**Comment by TheDiscordian** [comment]
Oh I may have misinterpreted your issue. You're talking Discord -> Matrix, you're absolutely correct, my apologies. It makes total sense to block while sending the message, then send image to the chat.

Process like:
* Get Discord imagemessage
* Send message to Matrix, wait for some sort of sent confirmation
* Send image to Matrix

I wonder how hard it'd be to do.

**Comment by Sorunome** [comment]
somewhat related with #68

**Comment by Sorunome** [comment]
Fixed by now
